// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonjurTask.Data;

#nullable disable

namespace MonjurTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231130102907_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MonjurTask.Models.CorporateCustomer", b =>
                {
                    b.Property<int>("CorporateCustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorporateCustomerID"), 1L, 1);

                    b.Property<string>("CorporateCustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CorporateCustomerID");

                    b.ToTable("Corporate_Customer_Tbl");

                    b.HasData(
                        new
                        {
                            CorporateCustomerID = 1,
                            CorporateCustomerName = "Abdullah"
                        },
                        new
                        {
                            CorporateCustomerID = 2,
                            CorporateCustomerName = "Monjur"
                        },
                        new
                        {
                            CorporateCustomerID = 3,
                            CorporateCustomerName = "Rakib"
                        });
                });

            modelBuilder.Entity("MonjurTask.Models.IndividualCustomer", b =>
                {
                    b.Property<int>("IndividualCustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndividualCustomerID"), 1L, 1);

                    b.Property<string>("IndividualCustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IndividualCustomerID");

                    b.ToTable("Individual_Customer_Tbl");

                    b.HasData(
                        new
                        {
                            IndividualCustomerID = 1,
                            IndividualCustomerName = "Nayeem"
                        },
                        new
                        {
                            IndividualCustomerID = 2,
                            IndividualCustomerName = "Emran"
                        },
                        new
                        {
                            IndividualCustomerID = 3,
                            IndividualCustomerName = "Saleh"
                        });
                });

            modelBuilder.Entity("MonjurTask.Models.MeetingMinuteDetail", b =>
                {
                    b.Property<int>("MeetingMinuteDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingMinuteDetailID"), 1L, 1);

                    b.Property<int>("MeetingMinuteMasterID")
                        .HasColumnType("int");

                    b.Property<int>("ProductServiceID")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("MeetingMinuteDetailID");

                    b.HasIndex("MeetingMinuteMasterID");

                    b.HasIndex("ProductServiceID");

                    b.ToTable("Meeting_Minutes_Details_Tbl");
                });

            modelBuilder.Entity("MonjurTask.Models.MeetingMinuteMaster", b =>
                {
                    b.Property<int>("MeetingMinuteMasterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingMinuteMasterID"), 1L, 1);

                    b.Property<string>("Agenda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttendsFromClient")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AttendsFromHost")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("CorporateCustomerID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discussion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IndividualCustomerID")
                        .HasColumnType("int");

                    b.Property<string>("MeetingPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("MeetingMinuteMasterID");

                    b.HasIndex("CorporateCustomerID");

                    b.HasIndex("IndividualCustomerID");

                    b.ToTable("Meeting_Minutes_Master_Tbl");
                });

            modelBuilder.Entity("MonjurTask.Models.ProductService", b =>
                {
                    b.Property<int>("ProductServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductServiceID"), 1L, 1);

                    b.Property<string>("ProductServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("ProductServiceID");

                    b.ToTable("Products_Service_Tbl");

                    b.HasData(
                        new
                        {
                            ProductServiceID = 1,
                            ProductServiceName = "Laptop",
                            Unit = 5
                        },
                        new
                        {
                            ProductServiceID = 2,
                            ProductServiceName = "Website making",
                            Unit = 10
                        },
                        new
                        {
                            ProductServiceID = 3,
                            ProductServiceName = "Mouse",
                            Unit = 8
                        },
                        new
                        {
                            ProductServiceID = 4,
                            ProductServiceName = "Keyboard",
                            Unit = 15
                        },
                        new
                        {
                            ProductServiceID = 5,
                            ProductServiceName = "web hosting",
                            Unit = 12
                        });
                });

            modelBuilder.Entity("MonjurTask.Models.MeetingMinuteDetail", b =>
                {
                    b.HasOne("MonjurTask.Models.MeetingMinuteMaster", "MeetingMinuteMaster")
                        .WithMany("MeetingMinuteDetails")
                        .HasForeignKey("MeetingMinuteMasterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonjurTask.Models.ProductService", "ProductService")
                        .WithMany("MeetingMinuteDetails")
                        .HasForeignKey("ProductServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeetingMinuteMaster");

                    b.Navigation("ProductService");
                });

            modelBuilder.Entity("MonjurTask.Models.MeetingMinuteMaster", b =>
                {
                    b.HasOne("MonjurTask.Models.CorporateCustomer", "CorporateCustomer")
                        .WithMany("MeetingMinuteMasters")
                        .HasForeignKey("CorporateCustomerID");

                    b.HasOne("MonjurTask.Models.IndividualCustomer", "IndividualCustomer")
                        .WithMany("MeetingMinuteMasters")
                        .HasForeignKey("IndividualCustomerID");

                    b.Navigation("CorporateCustomer");

                    b.Navigation("IndividualCustomer");
                });

            modelBuilder.Entity("MonjurTask.Models.CorporateCustomer", b =>
                {
                    b.Navigation("MeetingMinuteMasters");
                });

            modelBuilder.Entity("MonjurTask.Models.IndividualCustomer", b =>
                {
                    b.Navigation("MeetingMinuteMasters");
                });

            modelBuilder.Entity("MonjurTask.Models.MeetingMinuteMaster", b =>
                {
                    b.Navigation("MeetingMinuteDetails");
                });

            modelBuilder.Entity("MonjurTask.Models.ProductService", b =>
                {
                    b.Navigation("MeetingMinuteDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
